import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JS Mastery',
  description: 'Generated by create next app',
  other:{
    'theme-color': '#0d1117',
    "color-scheme": "dark only",
    "twitter:image": "https://cdn.pixabay.com/photo/2018/08/14/13/23/ocean-3605547_1280.jpg",
    "twiter:card": "summary_large_image",
    "og:url": "jsmastery.pro",
    "og:image": 'https://cdn.pixabay.com/photo/2018/08/14/13/23/ocean-3605547_1280.jpg',
    "og:type": 'website',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-black-100 font-poppins'>{children}</body>
    </html>
  )
}
